# Generated by Django 4.1.3 on 2023-01-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('Art', 'Art'), ('Game Dev', 'Game Dev'), ('R U Ready? Characters', 'R U Ready? Characters'), ('PC Builds', 'PC Builds'), ('Accolades', 'Accolades')], default=False, max_length=200)),
            ],
        ),
    ]
