# Generated by Django 4.1.3 on 2023-02-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='series')),
                ('summary', models.TextField()),
                ('entry', models.CharField(blank=True, choices=[('Self-Portraits', 'Self-Portraits'), ('Characters', 'Characters'), ('Sketches', 'Sketches'), ('Mixed-Media', 'Mixed-Media'), ('Hatching', 'Hatching'), ('Portraits', 'Portraits'), ('Imagined Portaits', 'Imagined Portraits')], default=False, max_length=200)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Works of Art',
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('summary', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('Novel', 'Novel'), ('Comic Book', 'Comic Book')], default=False, max_length=200)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Literature',
            },
        ),
        migrations.CreateModel(
            name='Vis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='vids')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Visuals',
            },
        ),
    ]
