# Generated by Django 4.1.3 on 2023-05-24 21:09

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=100)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Visuals',
            },
        ),
        migrations.DeleteModel(
            name='Vis',
        ),
    ]
