# Generated by Django 4.1.3 on 2023-05-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_visual_delete_vis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visual',
            old_name='url',
            new_name='link',
        ),
    ]
