# Generated by Django 4.1.3 on 2023-02-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bio', '0002_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('summary', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('Novel', 'Novel'), ('Comic Book', 'Comic Book')], default=False, max_length=200)),
                ('pdf', models.FileField(upload_to='pdf')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
