# Generated by Django 4.1.3 on 2023-05-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_rename_url_visual_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Collection',
            },
        ),
    ]
