# Generated by Django 4.1.3 on 2023-02-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='literature',
            options={'verbose_name_plural': 'Literature'},
        ),
    ]
