# Generated by Django 4.1.3 on 2023-02-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0004_alter_literature_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
