# Generated by Django 4.1.3 on 2023-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0004_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AlterField(
            model_name='literature',
            name='category',
            field=models.CharField(blank=True, choices=[('Novel', 'Novel'), ('Comic Book', 'Comic Book'), ('Magazine', 'Magazine'), ('Flyer', 'Flyer')], default=False, max_length=200),
        ),
    ]
