# Generated by Django 4.1.3 on 2023-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_alter_literature_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
