# Generated by Django 4.1.3 on 2023-02-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0006_alter_literature_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='cover_image',
            new_name='img',
        ),
    ]
