# Generated by Django 4.1.3 on 2023-07-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0006_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
    ]
