# Generated by Django 4.1.3 on 2023-02-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0007_rename_cover_image_literature_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='series')),
                ('summary', models.TextField()),
                ('entry', models.CharField(blank=True, choices=[('Self-Portrait', 'Self-Portrait'), ('Characters', 'Characters'), ('Sketches', 'Sketches'), ('Mixed-Media', 'Mixed-Media'), ('Hatching', 'Hatching'), ('Portraits', 'Portraits'), ('Imagined Portaits', 'Imagined Portraits')], default=False, max_length=200)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Works of Art',
            },
        ),
    ]
