# Generated by Django 4.1.3 on 2023-02-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0008_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='entry',
            field=models.CharField(blank=True, choices=[('Self-Portraits', 'Self-Portraits'), ('Characters', 'Characters'), ('Sketches', 'Sketches'), ('Mixed-Media', 'Mixed-Media'), ('Hatching', 'Hatching'), ('Portraits', 'Portraits'), ('Imagined Portaits', 'Imagined Portraits')], default=False, max_length=200),
        ),
    ]
