# Generated by Django 5.1.2 on 2025-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0008_artwork_completed_date_literature_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='category',
            field=models.CharField(blank=True, choices=[('Novel', 'Novel'), ('Comic Book', 'Comic Book'), ('Magazine', 'Magazine'), ('Flyer', 'Flyer'), ('Essays', 'Essays')], default=False, max_length=200),
        ),
    ]
