# Generated by Django 5.1.2 on 2025-03-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0009_alter_literature_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='category',
            field=models.CharField(blank=True, choices=[('Novel', 'Novel'), ('Comic Book', 'Comic Book'), ('Magazine', 'Magazine'), ('Flyer', 'Flyer'), ('Essay', 'Essay')], default=False, max_length=200),
        ),
    ]
